---
version: 2
jobs:
  build-backend:
    docker:
      - image: circleci/node:7
    steps:
      - checkout
      - run: cd backend && npm install
  
  build-frontend:
    docker:
      - image: circleci/node:7
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-npm-{{ .Branch }}-{{ checksum "frontend/package.json" }}
            - v1-npm-{{ .Branch }}
            - v1-npm
      
      - run: cd frontend && npm install

      - save_cache:
          key: v1-npm-{{ .Branch }}-{{ checksum "frontend/package.json" }}
          paths:
            - frontend/node_modules

      - run: cd frontend && npm run build
         
  deploy:
    docker:
      - image: stackbuilders/hapistrano:latest
    steps:
      - checkout
      - run: echo -e "Host * \n  StrictHostKeyChecking no" >> ~/.ssh/config
      - run:
          name: Deploy to staging
          no_output_timeout: 30m
          command: hap deploy -c deploy/cloud.yml        

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build-backend
      - build-frontend
      - deploy:
          requires:
            - build-backend
            - build-frontend

