---
nginx_configs:
  proxy:
    - proxy_set_header X-Real-IP  $remote_addr
    - proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for
    - proxy_set_header Host $host
    - proxy_connect_timeout 90s
    - proxy_send_timeout 90s
    - proxy_read_timeout 90s
    - proxy_buffer_size 4k
    - proxy_buffers 4 32k
    - proxy_busy_buffers_size 64k
    - proxy_temp_file_write_size 64k

nginx_sites:
  default:
    - listen 80 default_server
    - server_name {{ domain_name }}
    - return 302 https://$server_name$request_uri

  secure:
    - listen 443 ssl
    - server_name {{ domain_name }}
    - ssl on
    - ssl_certificate {{ certbot_certificates_path }}/{{ domain_name }}/fullchain.pem
    - ssl_certificate_key {{ certbot_certificates_path }}/{{ domain_name }}/privkey.pem
    - ssl_dhparam {{ certbot_certificates_path }}/dhparam.pem
    - ssl_session_timeout 5m
    - ssl_prefer_server_ciphers on
    - location / {
        proxy_pass http://localhost:3001;
        proxy_redirect off;
        client_max_body_size 10m;
        client_body_buffer_size 128k;
        add_header Strict-Transport-Security "max-age=31536000; includeSubDomains";
      }
