---
- hosts: cloud
  become: true
  
  roles:
    - role: set-hostname
      tags: set-hostname

    - role: jdauphant.nginx
      nginx_http_params:
        - sendfile "on"
        - access_log "/var/log/nginx/access.log"
    
    - role: geerlingguy.nodejs
      tags: nodejs
      nodejs_version: "8.x"
    
    - role: ssh-keys
      tags: ssh

    - role: default-apps
      tags: apps

    - role: networking
      tags: networking

    - role: certbot
      tags: certbot

    - role: env-var
      tags: env-var
    
    - role: deploy-cloud
      tags: deploy-cloud
