---
- hosts: cloud
  become: true
  
  roles:
    - role: set-hostname
      tag: set-hostname

    - role: jdauphant.nginx
      nginx_http_params:
        - sendfile "on"
        - access_log "/var/log/nginx/access.log"
     
    - role: geerlingguy.nodejs
      tag: nodejs
      nodejs_version: "8.x"
    
    - role: ssh-keys
      tag: ssh

    - role: default-apps
      tag: apps

    - role: networking
      tag: networking

    - role: certbot
      tag: certbot

    - role: env-var
      tag: env-var

