---

- hosts: database
  become: true

  roles:
    - role: set-hostname
      tag: set-hostname
    
    - role: geerlingguy.postgresql
      tag: database

    - role: ssh-keys
      tag: ssh

    - role: default-apps
      tag: apps


