# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
# General Vagrant VM configuration.
config.vm.box = "debian/stretch64"
config.ssh.insert_key = false
config.vm.synced_folder ".", "/vagrant", disabled: true
config.vm.provider :virtualbox do |v|
v.memory = 1024
v.linked_clone = true
end

# Application server 1.
config.vm.define "webserver" do |app|
app.vm.hostname = "webserver"
app.vm.network :forwarded_port, guest: 80, host: 8080
app.vm.network "public_network"
end

# Database server.
config.vm.define "database" do |db|
db.vm.hostname = "database"
db.vm.network "public_network"
end
end
